#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : enable
#pragma optionEXT (unroll all)
#include "../constants.h"
#include "defines.glsl"
#include "rt_helper.glsl"
#include "sky.glsl"
#include "random.glsl"
#include "globalTexture.glsl"
#include "vertexData.glsl"
#include "gbuffer.glsl"

// Bindings
layout(binding = BINDING_OFFSET_GLOBAL_UBO, set = 0) uniform global_ubo
{
	GlobalUbo ubo;
};
layout(binding = BINDING_OFFSET_GLOBAL_UBO_PREV, set = 0) uniform global_ubo_prev
{
	GlobalUbo uboPrev;
};
#include "traceRay.glsl"
#include "reflectTrace.glsl"
#include "lights.glsl"

vec3 reflect_point_vs_plane(vec3 plane_pt, vec3 plane_normal, vec3 point)
{
	return point - 2 * plane_normal * dot(plane_normal, point - plane_pt);
}

float ray_distance_to_plane(vec3 plane_pt, vec3 plane_normal, vec3 ray_origin, vec3 ray_direction)
{
	return dot(plane_pt - ray_origin, plane_normal) / dot(ray_direction, plane_normal);
}


// vec4 calculateReflection(inout vec3 pos, inout vec3 direction, inout vec3 N){
// 	vec3 dirReflection = reflect(direction, N);

// 	Ray ray;
// 	ray.origin = pos;
// 	ray.direction = dirReflection;
// 	ray.t_min = 0.01;
// 	ray.t_max = 10000.0;
// 	if(dot(ray.direction, N) >= 0)
// 		ray.origin -= ray.direction * 0.001;
// 	else
// 		ray.origin -= N * 0.001;
// 	traceRay(ray, RAY_MIRROR_OPAQUE_VISIBLE | RAY_MIRROR_PARTICLE_VISIBLE);

// 	vec4 albedoReflection = vec4(0);
// 	if(!found_intersection(rp)){
// 		albedoReflection = sampleSky(ray.direction);
// 	} else {
// 		HitPoint hp = getHitPoint(rp);
// 		//Triangle triangle = getTriangle(rp);
// 		vec4 tex = getTextureWithLod(hp,0);
// 		albedoReflection = tex;


// 		pos = hp.pos;
// 		direction = dirReflection;
// 		N = hp.normal;
// 		//albedoReflection = vec4(calcShade(pos, N, albedoReflection.xyz, hp.cluster), albedoReflection.w);
// 		albedoReflection = vec4(calcShading(albedoReflection, hp.pos, hp.normal, hp.cluster, hp.material),1);
// 	}
// 	return albedoReflection;
// }

// vec4 calculateRefraction( inout vec3 pos, inout vec3 direction, inout vec3 N, in float n1, in float n2){
// 	vec3 dirRefraction = refract( direction, N, n2/n1 );
// 	dirRefraction = refract( dirRefraction, N, n1/n2 );

// 	Ray ray;
// 	ray.origin = pos;
// 	ray.direction = dirRefraction;
// 	ray.t_min = 0.01;
// 	ray.t_max = 10000.0;
// 	if(dot(ray.direction, N) >= 0)
// 		ray.origin -= ray.direction * 0.001;
// 	else
// 		ray.origin -= N * 0.001;

// 	traceRay(ray, RAY_MIRROR_OPAQUE_VISIBLE | RAY_MIRROR_PARTICLE_VISIBLE);
// 	vec4 albedoRefraction = vec4(0);
// 	if(!found_intersection(rp)){
// 		albedoRefraction = sampleSky(ray.direction);
// 	} else {
// 		HitPoint hp = getHitPoint(rp);
// 		//Triangle triangle = getTriangle(rp);
// 		vec4 tex = getTextureWithLod(hp,0);
// 		albedoRefraction = tex;// * tex.w + albedoRefraction * (1-tex.w);

// 		pos = hp.pos;
// 		direction = normalize(dirRefraction);
// 		N = hp.normal;
// 		//albedoRefraction = vec4(calcShade(pos, N, albedoRefraction.xyz, hp.cluster), albedoRefraction.w);
// 		albedoRefraction = vec4(calcShading(albedoRefraction, hp.pos, hp.normal, hp.cluster, hp.material),1);
// 	}
// 	return albedoRefraction;
// }



// vec4 second(in vec3 pos, in vec3 direction, in vec3 N){
// 	vec4 color = vec4(0);
// 	float n1, n2, ndotr = dot(direction, N);  
// 	if( ndotr > 0.0f ) {
// 		n1 = 1.0; 
// 		n2 = 1.5;
// 		N = -N;
// 	} else {
// 		n1 = 1.5;
// 		n2 = 1.0; 
// 	}

// 	//float F = pow(1.0 - max(0.0, -dot(direction, N)), 5.0);
// 	//F = mix(0.5, 1.0, F);

// 	vec3 P_reflection = pos;
// 	vec3 N_reflection = N;
// 	vec3 ViewDir_reflection = direction;
// 	vec4 albedoReflection = calculateReflection(P_reflection, ViewDir_reflection, N_reflection);

// 	vec3 P_refraction = pos;
// 	vec3 N_refraction = N;
// 	vec3 ViewDir_refraction = direction;
// 	vec4 albedoRefraction = calculateRefraction(P_refraction, ViewDir_refraction, N_refraction, n1, n2);

// 	float r0 = (n1-n2)/(n1+n2); r0 *= r0;
// 	float fresnel = r0 + (1.-r0) * pow(1.0-abs(ndotr),5.);
// 	float ratio = fresnel;//0.2;
// 	vec4 albedo = ratio * albedoReflection + (1 - ratio) * albedoRefraction;

// 	color = albedo;
// 	return color;
// }


// void reflectionRefrection(){
// 	vec4 primary_albedo;
// 	vec3 normal;
// 	vec3 pos;
// 	uint cluster;
// 	uint material;
// 	float depth;
// 	vec3 motion;
// 	vec3 originalDir;

// 	vec4 temp;
// 	uvec4 utemp;
// 	utemp = imageLoad(objectGBuffer, ivec2(gl_LaunchIDEXT.xy));
// 	material = utemp.x;
// 	cluster = utemp.y;
// 	if (!isGlass(material) && !isMirror(material) && !isWater(material)) return;

// 	primary_albedo = imageLoad(albedoGBuffer, ivec2(gl_LaunchIDEXT.xy));
// 	normal = imageLoad(normalGBuffer, ivec2(gl_LaunchIDEXT.xy)).xyz;
// 	pos = imageLoad(posGBuffer, ivec2(gl_LaunchIDEXT.xy)).xyz;
// 	originalDir = imageLoad(viewGBuffer, ivec2(gl_LaunchIDEXT.xy)).xyz;

// 	vec3 P = pos;
// 	vec3 N = normalize(normal);
// 	vec3 shadeColor = primary_albedo.xyz;
// 	vec3 viewDir = normalize(P - ubo.camPos.xyz);

// 	vec4 color = vec4(0);
// 	if (isGlass(material)){
// 			float n1, n2, ndotr = dot(viewDir, N);  
// 			if( ndotr > 0.0f ) {
// 				n1 = 1.0; 
// 				n2 = 1.5;
// 				N = -N;
// 			} else {
// 				n1 = 1.5;
// 				n2 = 1.0; 
// 			}

// 			//float F = pow(1.0 - max(0.0, -dot(viewDir, N)), 5.0);
// 			//F = mix(0.5, 1.0, F);

// 			vec3 P_reflection = P;
// 			vec3 N_reflection = N;
// 			vec3 ViewDir_reflection = viewDir;
// 			vec4 albedoReflection = calculateReflection(P_reflection, ViewDir_reflection, N_reflection);
// 			if(isGlass(get_material(rp))){
// 				albedoReflection = calculateReflection(P_reflection, ViewDir_reflection, N_reflection);
// 			}

// 			vec3 P_refraction = P;
// 			vec3 N_refraction = N;
// 			vec3 ViewDir_refraction = viewDir;
// 			vec4 albedoRefraction = calculateRefraction(P_refraction, ViewDir_refraction, N_refraction, n1, n2);
	
// 			Ray ray;
// 			ray.origin = P;
// 			ray.direction = originalDir;
// 			ray.t_min = 0.01;
// 			ray.t_max = 10000.0;
// 			trace_ray(ray, RAY_MIRROR_OPAQUE_VISIBLE | RAY_MIRROR_PARTICLE_VISIBLE);

// 			if(found_intersection(rp)){
// 				if(isGlass(get_material(rp))){
// 					HitPoint hp = getHitPoint(rp);
// 					vec4 al = getTextureWithLod(hp,0);
// 					vec3 dir = normalize(hp.pos - ubo.camPos.xyz);
// 					vec3 norm = normalize(hp.normal);
// 					if(dot(norm, dir) > 0) norm = -norm;
// 					vec4 sec = second(hp.pos, dir, norm);

// 					albedoRefraction = al * al.w + sec * (1-al.w);
// 				}
// 			}
// 			// if(isGlass(get_material(rp))){
// 			// 	float n12, n22, ndotr2 = dot(viewDir, N);  
// 			// 	if( ndotr2 > 0.0f ) {
// 			// 		n12 = 1.0; 
// 			// 		n22 = 1.5;
// 			// 		N = -N;
// 			// 	} else {
// 			// 		n12 = 1.5;
// 			// 		n22 = 1.0; 
// 			// 	}
// 			// 	albedoRefraction = calculateRefraction(P, viewDir, N, n12, n22);
// 			// }

// 			float r0 = (n1-n2)/(n1+n2); r0 *= r0;
// 			float fresnel = r0 + (1.-r0) * pow(1.0-abs(ndotr),5.);
// 			float ratio = 0.2;//0.2;
// 			vec4 albedo = ratio * albedoReflection + (1 - ratio) * albedoRefraction;

// 			if(primary_albedo.w != 0) primary_albedo = vec4(calcShading(primary_albedo, P, N, cluster, material),primary_albedo.w);
// 			color = primary_albedo * primary_albedo.w + albedo * (1-primary_albedo.w);
// 			//color = vec4(color.xyz, primary_albedo.w);

// 			//material = get_material(rp);
			
// 		//}
// 	} else if(isWater(material)){
// 		//for(int i =0; i< 2; i++){
// 			float n1, n2, ndotr = dot(viewDir, N);  
// 			if( ndotr > 0.0f ) {
// 				n1 = 1.0; 
// 				n2 = 1.3;
// 				N = -N;
// 			} else {
// 				n1 = 1.3;
// 				n2 = 1.0; 
// 			}

// 			vec3 P_reflection = P;
// 			vec3 N_reflection = N;
// 			vec3 ViewDir_reflection = viewDir;
// 			vec4 albedoReflection = calculateReflection(P_reflection, ViewDir_reflection, N_reflection);
// 			if(isGlass(get_material(rp))){
// 				albedoReflection = calculateReflection(P_reflection, ViewDir_reflection, N_reflection);
// 			}

// 			vec3 P_refraction = P;
// 			vec3 N_refraction = N;
// 			vec3 ViewDir_refraction = viewDir;
// 			vec4 albedoRefraction = calculateRefraction(P_refraction, ViewDir_refraction, N_refraction, n1, n2);

// 			float r0 = (n1-n2)/(n1+n2); r0 *= r0;
// 			float fresnel = r0 + (1.-r0) * pow(1.0-abs(ndotr),5.);
// 			float ratio = fresnel;//0.2;
// 			vec4 albedo = ratio * albedoReflection + (1 - ratio) * albedoRefraction;

// 			primary_albedo = vec4(calcShading(primary_albedo, P, N, cluster, material),primary_albedo.w);
// 			//color = primary_albedo * primary_albedo.w + albedo * (1-primary_albedo.w);
// 			color.xyz = (albedo.xyz) * primary_albedo.xyz;//alpha_blend( albedo, primary_albedo);
// 			color.w = primary_albedo.w;
// 			//color = vec4(color.xyz, primary_albedo.w);

// 			//material = get_material(rp); 
			
// 		//}
// 	} else if(isMirror(material)){
// 		vec4 mirrorColor = primary_albedo;
// 		mirrorColor = 1 - vec4(mirrorColor/1);
// 		// 1 - vec4(src/1)
// 		vec4 reflection = calculateReflection(P, viewDir, N);
// 		color = vec4(mirrorColor.xyz * reflection.xyz,1);

// 	} 
	//imageStore(normalGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(normal.xyz,1));
	//imageStore(posGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(pos.xyz, 0));
	//imageStore(objectGBuffer, ivec2(gl_LaunchIDEXT.xy), uvec4(material, cluster, 0,0));
	//imageStore(reflectionGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(color));



#define PRIMARY_RAY_T_MAX (10000.0)
Ray
getPrimaryRay(vec2 pos_cs)
{
	vec4 v_near = ubo.inverseViewMat * ubo.inverseProjMat * vec4(pos_cs, -1, 1.0);
	vec4 v_far  = ubo.inverseViewMat * ubo.inverseProjMat * vec4(pos_cs,  1, 1.0);
	v_near /= v_near.w;
	v_far  /= v_far.w;

	Ray ray;
	ray.origin = v_near.xyz;
	ray.direction = normalize(v_far.xyz - v_near.xyz);
	ray.t_min = 0.01;
	ray.t_max = PRIMARY_RAY_T_MAX;

	return ray;
}

void main() 
{
	vec4 primary_albedo;
	vec3 normal;
	vec3 pos;
	uint cluster;
	uint material;
	float depth;
	vec3 motion;
	vec3 originalDir;

	vec4 temp;
	uvec4 utemp;
	//utemp = imageLoad(objectGBuffer, ivec2(gl_LaunchIDEXT.xy));
	material = uint(imageLoad(viewGBuffer, ivec2(gl_LaunchIDEXT.xy)).w);
	if (!isGlass(material) && !isMirror(material) && !isWater(material) && !isSeeThrough(material) && !isSeeThroughNoAlpha(material)) return;
	
	normal = imageLoad(normalGBuffer, ivec2(gl_LaunchIDEXT.xy)).xyz;
	pos = imageLoad(posGBuffer, ivec2(gl_LaunchIDEXT.xy)).xyz;
	cluster = uint(imageLoad(posGBuffer, ivec2(gl_LaunchIDEXT.xy)).w);

	primary_albedo = imageLoad(albedoGBuffer, ivec2(gl_LaunchIDEXT.xy));
	originalDir = imageLoad(viewGBuffer, ivec2(gl_LaunchIDEXT.xy)).xyz;

	vec3 P = pos;
	vec3 N = normalize(normal);
	vec3 shadeColor = primary_albedo.xyz;
	vec3 viewDir = normalize(P - ubo.camPos.xyz);
	vec4 color = vec4(0);

	const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
	const vec2 inUV = pixelCenter/vec2(gl_LaunchSizeEXT.xy);
	const vec2 screenCoordClipSpace  = inUV * 2.0 - 1.0;
	rp_reflect.sccs = screenCoordClipSpace;
	rp_reflect.transparent = vec4(0);

	if (isMirror(material)){
		vec4 albedoReflection;
		rp_reflect.color = vec4(0);
		rp_reflect.depth = 0;
		traceReflect(pos, originalDir, N, false);

		vec4 mirrorColor = primary_albedo;
		mirrorColor = 1 - vec4(mirrorColor/1);
		vec4 color = vec4(mirrorColor.xyz * rp_reflect.color.xyz,1);


		vec3 new_position = rp_reflect.pos;
		vec3 new_pos_prev = rp_reflect.prevPos;

		vec3 ref_pos_curr, ref_pos_prev;
		vec3 ref_geo_normal;
		// compute the apparent position of the reflected or refracted object
		ref_pos_curr = reflect_point_vs_plane(P, N, new_position);
		ref_pos_prev = reflect_point_vs_plane(P, N, new_pos_prev);
		ref_geo_normal = reflect(rp_reflect.normal.xyz, N);
		
		Ray ray_0 = getPrimaryRay(screenCoordClipSpace);
		Ray ray_x = getPrimaryRay(screenCoordClipSpace + vec2(1.0 / float(ubo.width), 0));
		Ray ray_y = getPrimaryRay(screenCoordClipSpace + vec2(0, 1.0 / float(ubo.height)));

		float depth_vs_0 = ray_distance_to_plane(ref_pos_curr, ref_geo_normal, ubo.camPos.xyz, ray_0.direction);
		float depth_vs_x = ray_distance_to_plane(ref_pos_curr, ref_geo_normal, ubo.camPos.xyz, ray_x.direction);
		float depth_vs_y = ray_distance_to_plane(ref_pos_curr, ref_geo_normal, ubo.camPos.xyz, ray_y.direction);

		vec4 point = ubo.projMat * ubo.viewMat * vec4(ref_pos_curr.xyz, 1.0);
		vec4 pointPrev = uboPrev.projMat * uboPrev.viewMat * vec4(ref_pos_prev.xyz,1.0);
		vec3 ndc = point.xyw;
		vec3 ndcPrev = pointPrev.xyw;
		ndc.xy /= ndc.z;
		ndcPrev.xy /= ndcPrev.z;
		float fwidth_depth = 1.0 / max(1e-4, (abs(depth_vs_x - ndc.z) + abs(depth_vs_y - ndc.z)));

		vec4 motion = vec4((ndcPrev.xy - ndc.xy), -(ndcPrev.z - ndc.z), fwidth_depth);

		if(rp_reflect.hit_distance > rp_reflect.max_transparent_distance){
			vec4 trans = imageLoad(transparentGBuffer, ivec2(gl_LaunchIDEXT.xy));
			trans.xyz += rp_reflect.transparent.xyz;
			imageStore(transparentGBuffer, ivec2(gl_LaunchIDEXT.xy), trans);
		}

		imageStore(albedoGBuffer, ivec2(gl_LaunchIDEXT.xy), color);
		imageStore(normalGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(rp_reflect.normal.xyz, -ndc.z));//rp_reflect.depth));
		imageStore(posGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(rp_reflect.pos.xyz, rp_reflect.cluster));
		imageStore(objectGBuffer, ivec2(gl_LaunchIDEXT.xy), rp_reflect.object);
		imageStore(viewGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(originalDir, rp_reflect.material));
		imageStore(motionGBuffer, ivec2(gl_LaunchIDEXT.xy), motion);

	}
	if (isGlass(material)){
		// if texture (alpha) not see through enough then do not trace further
		if(primary_albedo.w > 0.5) return;

		float n1 = 1.5, n2 = 1.0, ndotr = dot(originalDir, N);  
		if( ndotr > 0.0f ) {
			N = -N;
		}

		bool ego = isPlayer(material);

		vec4 albedoReflection;
		vec4 albedoRefraction;
		rp_reflect.color = vec4(0);
		rp_reflect.depth = 0;
		traceReflect(pos, originalDir, N, ego);
		albedoReflection = rp_reflect.color;

		rp_reflect.color = vec4(0);
		rp_reflect.depth = 0;
		traceRefract(pos, originalDir, N, n1, n2, ego);
		albedoRefraction = rp_reflect.color;

		float r0 = (n1-n2)/(n1+n2); r0 *= r0;
		float fresnel = r0 + (1.-r0) * pow(1.0-abs(ndotr),5.);
		float ratio = fresnel*2;
		if(rp_reflect.material == MATERIAL_KIND_SKY ) {
			albedoReflection *= 0.5;
			ratio = fresnel;
		}
		vec4 albedo = ratio * albedoReflection + (1 - ratio) * albedoRefraction;

	

		vec4 color = primary_albedo * primary_albedo.w + albedo * (1-primary_albedo.w);
		imageStore(reflectionGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(color.xyz,1));
		imageStore(albedoGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(color.xyz,1));
		imageStore(normalGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(rp_reflect.normal.xyz, rp_reflect.material));
		imageStore(posGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(rp_reflect.pos.xyz, rp_reflect.cluster));
		
		
	}
	if (isWater(material)){
		// if texture (alpha) not see through enough then do not trace further
		// water has no alpha

		float n1 = 1.3, n2 = 1.0, ndotr = dot(originalDir, N);  
		if( ndotr > 0.0f ) {
			N = -N;
		}

		vec4 albedoReflection;
		vec4 albedoRefraction;
		rp_reflect.color = vec4(0);
		rp_reflect.depth = 0;
		traceReflect(pos, originalDir, N, false);
		albedoReflection = rp_reflect.color;

		rp_reflect.color = vec4(0);
		rp_reflect.depth = 0;
		traceRefract(pos, originalDir, N, n1, n2, false);
		albedoRefraction = rp_reflect.color;

		float r0 = (n1-n2)/(n1+n2); r0 *= r0;
		float fresnel = r0 + (1.-r0) * pow(1.0-abs(ndotr),5.);
		float ratio = fresnel*2;
		vec4 albedo = ratio * albedoReflection + (1 - ratio) * albedoRefraction;

		//primary_albedo.w = 0.1;
		//vec4 color = primary_albedo * primary_albedo.w + albedo * (1-primary_albedo.w);
		vec4 color = albedo * primary_albedo;
		imageStore(reflectionGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(color.xyz,1));
		imageStore(albedoGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(color.xyz,1));
		imageStore(normalGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(rp_reflect.normal.xyz, rp_reflect.material));
		imageStore(posGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(rp_reflect.pos.xyz, rp_reflect.cluster));
		
		
	}
	if (isSeeThrough(material) || isSeeThroughNoAlpha(material)){
		if(primary_albedo.w > 0.5) return;
		primary_albedo.w =0;
		vec4 albedo;
		rp_reflect.color = vec4(0);
		rp_reflect.depth = 0;
		rp_reflect.addCount = 0;
		//rp_reflect.transparent = vec4(0);
		rp_reflect.max_transparent_distance = 0;
		traceStraight(pos, originalDir, N);
		albedo = rp_reflect.color;

		vec4 color = primary_albedo * primary_albedo.w + albedo * (1-primary_albedo.w);

		// vec4 trans = imageLoad(transparentGBuffer, ivec2(gl_LaunchIDEXT.xy));
		// 	vec4 cout = alpha_blend( trans, vec4(color.xyz,1));
		// imageStore(transparentGBuffer, ivec2(gl_LaunchIDEXT.xy), trans + color);
		//color += rp_reflect.transparent;
		vec4 trans = imageLoad(transparentGBuffer, ivec2(gl_LaunchIDEXT.xy));
		trans.xyz += rp_reflect.transparent.xyz;
		trans.w =0;
		imageStore(transparentGBuffer, ivec2(gl_LaunchIDEXT.xy), trans);

		imageStore(albedoGBuffer, ivec2(gl_LaunchIDEXT.xy), color);
		imageStore(normalGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(rp_reflect.normal.xyz,rp_reflect.material));
		imageStore(posGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(rp_reflect.pos.xyz, rp_reflect.cluster));
	}

	if(rp_reflect.material == MATERIAL_KIND_SKY ) {
		imageStore(objectGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(-1, -1, uintBitsToFloat(uvec2(~0u))));
		imageStore(motionGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(-1,-1,-1, 9999.0));
		imageStore(viewGBuffer, ivec2(gl_LaunchIDEXT.xy), vec4(originalDir.xyz, rp_reflect.material));
	}
}

