// AMD FidelityFX Super Resolution 1.0 - RCAS phase (robust contrast adaptive sharpening).
// MIT licensed, Copyright (c) 2021 Advanced Micro Devices, Inc. (see fsr/ffx_fsr1.h).
// Runs at native resolution on the tonemapped LDR result; EASU upscaling from a
// reduced render resolution is future work (needs render-scale infrastructure).
// Input transform intentionally empty: tonemapper output is display-referred LDR,
// exactly what RCAS expects (same as the FSR sample pipeline).
#version 460
#extension GL_GOOGLE_include_directive    : enable

#include "../constants.h"

#define A_GPU 1
#define A_GLSL 1
#include "fsr/ffx_a.h"
#define FSR_RCAS_F
#include "fsr/ffx_fsr1.h"

layout(binding = BINDING_OFFSET_RESULT, set = 0, rgba32f) uniform image2D resultImg;
layout(binding = BINDING_OFFSET_FSR_OUTPUT, set = 0, rgba32f) uniform image2D fsrImg;

layout(push_constant) uniform push {
    layout(offset = 0) uvec4 con;
};

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

AF4 FsrRcasLoadF(ASU2 p) { return AF4(imageLoad(resultImg, ivec2(p))); }
void FsrRcasInputF(inout AF1 r, inout AF1 g, inout AF1 b) {}

void main() {
    ivec2 ipos = ivec2(gl_GlobalInvocationID.xy);
    AF1 pixR, pixG, pixB;
    FsrRcasF(pixR, pixG, pixB, ASU2(ipos), con);
    imageStore(fsrImg, ipos, vec4(pixR, pixG, pixB, 1.0));
}
