#!/bin/bash
# Linux shader build for Quake III Arena R (Vulkan KHR ray tracing path).
# Requires Vulkan SDK env (source $VULKAN_SDK/../setup-env.sh), e.g.:
#   source /home/chazz/Downloads/1.4.363.0/setup-env.sh
#   ./compile.sh
set -e
cd "$(dirname "$0")"

if [ -z "$VULKAN_SDK" ]; then
  echo "ERROR: VULKAN_SDK not set. Source the SDK setup-env.sh first." >&2
  exit 1
fi
GLSL="$VULKAN_SDK/bin/glslangValidator"
SPVAS="$VULKAN_SDK/bin/spirv-as"
SPVVAL="$VULKAN_SDK/bin/spirv-val"
SPVDIS="$VULKAN_SDK/bin/spirv-dis"

GLSL_DIR="glsl"
SPV_DIR="spv"
HEADER_DIR="header"
# KHR ray tracing (SPV 1.5) needs Vulkan 1.2+ as compilation target.
RT_TARGET="--target-env vulkan1.2"

mkdir -p "$SPV_DIR" "$HEADER_DIR"

# --- SPIR-V -> C header (same shape as glslangValidator --vn output) ---
spv_to_header() { # $1=input.spv $2=varname $3=output.h
  python3 - "$1" "$2" "$3" <<'EOF'
import struct, sys
data = open(sys.argv[1], 'rb').read()
assert data[:4] == b'\x03\x02\x23\x07', 'not SPIR-V'
words = struct.unpack('<%dI' % (len(data) // 4), data)
name = sys.argv[2]
with open(sys.argv[3], 'w') as f:
    f.write('// generated by shader/compile.sh (glslangValidator + spirv-as)\n #pragma once\n')
    f.write('const uint32_t %s[] = {\n' % name)
    for i in range(0, len(words), 8):
        f.write('\t' + ','.join('0x%08x' % w for w in words[i:i+8]) + (',' if i + 8 < len(words) else '') + '\n')
    f.write('};')
EOF
}

compile_one() { # $1=src $2=varname $3=extra flags...
  local src="$1" var="$2"; shift 2
  local base
  base="$(basename "$src")"
  echo "compiling $base"
  "$GLSL" -DGLSL "$@" -V "$src" -o "$SPV_DIR/$base.spv"
  "$GLSL" -DGLSL "$@" -V "$src" --vn "$var" -o "$HEADER_DIR/$base.h"
  "$SPVVAL" --target-env vulkan1.2 "$SPV_DIR/$base.spv"
}

echo "== rasterizer =="
for f in "$GLSL_DIR"/rasterizer/*.vert; do
  n=$(basename "$f" .vert)
  compile_one "$f" "${n}Vert"
done
for f in "$GLSL_DIR"/rasterizer/*.frag; do
  n=$(basename "$f" .frag)
  compile_one "$f" "${n}Frag"
done

echo "== compute =="
for f in "$GLSL_DIR"/compute/*.comp; do
  n=$(basename "$f" .comp)
  compile_one "$f" "${n}Comp"
done

echo "== raytracer (KHR, strict) =="
for f in "$GLSL_DIR"/raytracer/*.rgen; do
  n=$(basename "$f" .rgen)
  compile_one "$f" "${n}RGen" $RT_TARGET
done
for f in "$GLSL_DIR"/raytracer/*.rmiss; do
  n=$(basename "$f" .rmiss)
  compile_one "$f" "${n}RMiss" $RT_TARGET
done
for f in "$GLSL_DIR"/raytracer/*.rchit; do
  n=$(basename "$f" .rchit)
  if [ "$n" = "reflect_rays" ]; then
    # -r: relaxes the ray-payload declaration check. reflect_rays.rchit
    # reads its incoming payload (IN@1) and fires nested traces (payload 1);
    # declaring an OUT payload at the same location is illegal, so the strict
    # check cannot be satisfied. Runtime behavior is unchanged.
    compile_one "$f" "${n}RCHit" $RT_TARGET -r
  else
    compile_one "$f" "${n}RCHit" $RT_TARGET
  fi
done

echo "== raytracer any-hit (KHR via SPV patch) =="
# glslang >=16 (SDK 1.4.x) only provides ignoreIntersectionNV/terminateRayNV;
# the EXT spelling is missing. Compile with NV enabled, then rewrite the
# module to pure KHR (same opcodes; NV forms are not terminators in the old
# grammar, so drop the dead branch after ignore/terminate) and validate.
for f in "$GLSL_DIR"/raytracer/*.rahit; do
  n=$(basename "$f" .rahit)
  echo "compiling $n.rahit"
  tmp="$(mktemp -d)"
  "$GLSL" -DGLSL $RT_TARGET -V "$f" -o "$tmp/out.spv"
  "$SPVDIS" "$tmp/out.spv" -o "$tmp/out.spvasm"
  python3 - "$tmp/out.spvasm" <<'EOF'
import sys
lines = open(sys.argv[1]).read().splitlines()
out = []
skip_dead = False
for ln in lines:
    s = ln.strip()
    if 'OpIgnoreIntersectionNV' in s or 'OpTerminateRayNV' in s:
        # KHR classifies ignore/terminate as block terminators (NV did not),
        # so any trailing branch/return/unreachable in the same block must go.
        out.append(ln.replace('IgnoreIntersectionNV', 'IgnoreIntersectionKHR').replace('TerminateRayNV', 'TerminateRayKHR'))
        skip_dead = True
        continue
    if skip_dead and (s.startswith('OpBranch') or s == 'OpReturn' or s.startswith('OpReturn ') or s == 'OpUnreachable'):
        continue
    skip_dead = False
    ln = ln.replace('SPV_NV_ray_tracing', 'SPV_KHR_ray_tracing').replace('RayTracingNV', 'RayTracingKHR')
    out.append(ln)
open(sys.argv[1], 'w').write('\n'.join(out) + '\n')
EOF
  "$SPVAS" --target-env spv1.5 "$tmp/out.spvasm" -o "$SPV_DIR/$n.rahit.spv"
  "$SPVVAL" --target-env vulkan1.2 "$SPV_DIR/$n.rahit.spv"
  spv_to_header "$SPV_DIR/$n.rahit.spv" "${n}RAHit" "$HEADER_DIR/$n.rahit.h"
  rm -rf "$tmp"
done

echo "ALL SHADERS BUILT + VALIDATED"
